version: 2
updates:
  # Configuration for Golang
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Configuration for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
